-define(DELIMITER, " ").
-define(ERROR, "-").
-define(SUCCESS_STR, "+").
-define(SUCCESS_INT, ":").
-define(CRLF, "\r\n").

-define(COMMAND_SUB, "sub").
-define(COMMAND_UNSUB, "unsub").
-define(COMMAND_PUB, "pub").
-define(COMMAND_QUIT, "quit").
-define(COMMAND_PING, "ping").
